/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorsRouteImport } from './routes/tutors'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FreeTrialRouteImport } from './routes/free-trial'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesIntermediateRouteImport } from './routes/courses.intermediate'
import { Route as CoursesBeginnerRouteImport } from './routes/courses.beginner'
import { Route as CoursesAdvancedRouteImport } from './routes/courses.advanced'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'

const TutorsRoute = TutorsRouteImport.update({
  id: '/tutors',
  path: '/tutors',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeTrialRoute = FreeTrialRouteImport.update({
  id: '/free-trial',
  path: '/free-trial',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesIntermediateRoute = CoursesIntermediateRouteImport.update({
  id: '/intermediate',
  path: '/intermediate',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesBeginnerRoute = CoursesBeginnerRouteImport.update({
  id: '/beginner',
  path: '/beginner',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesAdvancedRoute = CoursesAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/faqs': typeof FaqsRoute
  '/free-trial': typeof FreeTrialRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tutors': typeof TutorsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/advanced': typeof CoursesAdvancedRoute
  '/courses/beginner': typeof CoursesBeginnerRoute
  '/courses/intermediate': typeof CoursesIntermediateRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/free-trial': typeof FreeTrialRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tutors': typeof TutorsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/advanced': typeof CoursesAdvancedRoute
  '/courses/beginner': typeof CoursesBeginnerRoute
  '/courses/intermediate': typeof CoursesIntermediateRoute
  '/courses': typeof CoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/faqs': typeof FaqsRoute
  '/free-trial': typeof FreeTrialRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tutors': typeof TutorsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/advanced': typeof CoursesAdvancedRoute
  '/courses/beginner': typeof CoursesBeginnerRoute
  '/courses/intermediate': typeof CoursesIntermediateRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blogs'
    | '/contact'
    | '/courses'
    | '/faqs'
    | '/free-trial'
    | '/how-it-works'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/tutors'
    | '/courses/$slug'
    | '/courses/advanced'
    | '/courses/beginner'
    | '/courses/intermediate'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/blogs'
    | '/contact'
    | '/faqs'
    | '/free-trial'
    | '/how-it-works'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/tutors'
    | '/courses/$slug'
    | '/courses/advanced'
    | '/courses/beginner'
    | '/courses/intermediate'
    | '/courses'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blogs'
    | '/contact'
    | '/courses'
    | '/faqs'
    | '/free-trial'
    | '/how-it-works'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/tutors'
    | '/courses/$slug'
    | '/courses/advanced'
    | '/courses/beginner'
    | '/courses/intermediate'
    | '/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BlogsRoute: typeof BlogsRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  FaqsRoute: typeof FaqsRoute
  FreeTrialRoute: typeof FreeTrialRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TutorsRoute: typeof TutorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutors': {
      id: '/tutors'
      path: '/tutors'
      fullPath: '/tutors'
      preLoaderRoute: typeof TutorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-trial': {
      id: '/free-trial'
      path: '/free-trial'
      fullPath: '/free-trial'
      preLoaderRoute: typeof FreeTrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/intermediate': {
      id: '/courses/intermediate'
      path: '/intermediate'
      fullPath: '/courses/intermediate'
      preLoaderRoute: typeof CoursesIntermediateRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/beginner': {
      id: '/courses/beginner'
      path: '/beginner'
      fullPath: '/courses/beginner'
      preLoaderRoute: typeof CoursesBeginnerRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/advanced': {
      id: '/courses/advanced'
      path: '/advanced'
      fullPath: '/courses/advanced'
      preLoaderRoute: typeof CoursesAdvancedRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
  }
}

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesAdvancedRoute: typeof CoursesAdvancedRoute
  CoursesBeginnerRoute: typeof CoursesBeginnerRoute
  CoursesIntermediateRoute: typeof CoursesIntermediateRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesAdvancedRoute: CoursesAdvancedRoute,
  CoursesBeginnerRoute: CoursesBeginnerRoute,
  CoursesIntermediateRoute: CoursesIntermediateRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BlogsRoute: BlogsRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRouteWithChildren,
  FaqsRoute: FaqsRoute,
  FreeTrialRoute: FreeTrialRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TutorsRoute: TutorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
